### PR TITLE
Support more archive formats (cpio, ar)

### LINKED ISSUE #62: CPIO support
In addition to zip and tar it would be nice to also support cpio archives used by rpm packages (this format is handled by commons-compress).

### PR DESCRIPTION
**Pull request by ebourg**
This PR generalizes the tar stripper to other archive formats supported by Commons Compress. This fixes #62 and simplifies the code.

### CODE REVIEW

**Comment by Zlika** [comment]
Thank you Emmanuel for this PR. There seems to be some coding rules violations according to the CI. Could you please fix them?

**Comment by ebourg** [comment]
The code style is fixed but there is an issue with the integration tests, I'm investigating.

**Comment by ebourg** [comment]
It sould be good now

**Comment by Zlika** [comment]
Great, thanks!

**Comment by ebourg** [comment]
Thank you!

**Pull request merged**
