### PR TITLE
New Support for zip type extensions addZipType Support for custom pro…

### PR DESCRIPTION
**Pull request by lanlingxueyu**
…perties type file extensions addPropertiesFiles

1. Added support for zip type extensions addZipType
2. Added support for custom properties type file extensions addPropertiesFiles

### CODE REVIEW

**Comment by lanlingxueyu** [comment]
[reproducible-build-maven-plugin-master.zip](https://github.com/Zlika/reproducible-build-maven-plugin/files/2428154/reproducible-build-maven-plugin-master.zip)

**Comment by Zlika** [comment]
?? Why did you create 3 PR and close 2 of them?

**Comment by lanlingxueyu** [comment]
> ?? 为什么你创建3 PR并关闭其中2个？

Sorry, I will not use it, the operation error

**Comment by lanlingxueyu** [comment]
> ?? Why did you create 3 PR and close 2 of them?
Sorry, I will not use it, the operation error
Closed, others. Sorry

**Comment by lanlingxueyu** [comment]
[reproducible-build-maven-plugin-master.zip](https://github.com/Zlika/reproducible-build-maven-plugin/files/2430402/reproducible-build-maven-plugin-master.zip)

**Comment by lanlingxueyu** [comment]
[reproducible-build-maven-plugin-master.zip](https://github.com/Zlika/reproducible-build-maven-plugin/files/2431621/reproducible-build-maven-plugin-master.zip)

**Comment by lanlingxueyu** [comment]
> ?? Why did you create 3 PR and close 2 of them?

[reproducible-build-maven-plugin-master.zip](https://github.com/Zlika/reproducible-build-maven-plugin/files/2431624/reproducible-build-maven-plugin-master.zip)
Has been unable to compile through

**Pull request closed without merging**
