### PR TITLE
New parameters for strip-jar goal: zipDateTime and zipDateTimeFormatPattern

### PR DESCRIPTION
**Pull request by aksian**

### CODE REVIEW

**Comment by Zlika** [comment]
Great PR, thanks!

**Comment by aksian** [comment]
You are welcome :)
BTW, maybe you'd better remove the lines "<phase>package</phase>" from my example. They accidentally stayed out of my own project, where I needed to get the result exactly at the package phase. This can become a source of surprises, and, in general, it is better for most users not to play with the plugins execution order...

**Comment by Zlika** [comment]
Ok I will do that.
I know that using pre-integration-test as the default phase for strip:jar may not be ideal, but it's the only way I found to be sure that it will be executed after jar:jar.

**Comment by aksian** [comment]
In fact, this is quite a reasonable compromise. Nobody forbids changing the default settings :)

**Comment by Zlika** [comment]
As I don't have anything else in the pipeline at this time, I released version 0.6 of the plugin with your PR.
Thank you for this feature.

**Comment by aksian** [comment]
Thank you for such a quick release.

**Pull request merged**
