### PR TITLE
Feature/strip-jaxb also with the org.glassfish xjc implementation

### PR DESCRIPTION
**Pull request by nilsaellen**
* Add the default matchingCommentText applying to the org.glassfish xjc generator

* Add a mojo property to allow users to add an additional matchingCommentText

### CODE REVIEW

**Comment by Zlika** [comment]
Thanks!

**Comment by nilsaellen** [comment]
it's a pleasure! 

Do you plan to do a new release soon and to publish it to maven central?

**Comment by Zlika** [comment]
As soon as I have some time to do it :-)

**Comment by Zlika** [comment]
I'm releasing version 0.16 now. It should be available on Central soon.

**Pull request merged**
