### PR TITLE
Support jenkins plugin .hpi

### PR DESCRIPTION
**Pull request by lanlingxueyu**
support jenkins plugin .hpi package difference elimination
      1.MANIFEST.MF
      2.pom.properties
      3. *.stapler

### CODE REVIEW

**Comment by lanlingxueyu** [comment]
submitted

**Comment by Zlika** [comment]
???

**Comment by lanlingxueyu** [comment]
[Uploading reproducible-build-maven-plugin-master.zip…]()

**Comment by lanlingxueyu** [comment]
[Uploading reproducible-build-maven-plugin-master.zip…]()

**Pull request closed without merging**
